---
version: 2

jobs:
  test:
    docker:
    - image: circleci/golang:1.10
    working_directory: /go/src/github.com/prometheus/node_exporter

    steps:
    - checkout
    - run: make promu
    - run: make
    - run: rm -v node_exporter

  build:
    machine: true
    working_directory: /home/circleci/.go_workspace/src/github.com/prometheus/node_exporter

    environment:
      DOCKER_IMAGE_NAME: prom/node-exporter
      QUAY_IMAGE_NAME: quay.io/prometheus/node-exporter
      DOCKER_TEST_IMAGE_NAME: quay.io/prometheus/golang-builder:1.10-base
      REPO_PATH: github.com/prometheus/node_exporter

    steps:
    - checkout
    - attach_workspace:
        at: .
    - run: make promu
    - run: promu crossbuild -v
    - run: ln -s .build/linux-amd64/node_exporter node_exporter
    - run:
        command: |
          if [ -n "$CIRCLE_TAG" ]; then
            make docker DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME DOCKER_IMAGE_TAG=$CIRCLE_TAG
            make docker DOCKER_IMAGE_NAME=$QUAY_IMAGE_NAME DOCKER_IMAGE_TAG=$CIRCLE_TAG
          else
            make docker DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME
            make docker DOCKER_IMAGE_NAME=$QUAY_IMAGE_NAME
          fi
    - run: mkdir $CIRCLE_ARTIFACTS/binaries/ && cp -a .build/* $CIRCLE_ARTIFACTS/binaries/
    - run: docker images
    - run: docker run --rm -t -v "$(pwd):/app" "${DOCKER_TEST_IMAGE_NAME}" -i "${REPO_PATH}" -T
    - run: make test-docker DOCKER_IMAGE_TAG=$CIRCLE_TAG


  docker_hub_master:
    docker:
    - image: circleci/golang:1.10
    working_directory: /go/src/github.com/prometheus/node_exporter
    steps:
    - checkout
    - setup_remote_docker
    - docker login -e $DOCKER_EMAIL -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
    - docker login -e $QUAY_EMAIL -u $QUAY_LOGIN -p $QUAY_PASSWORD quay.io
    - docker push $DOCKER_IMAGE_NAME
    - docker push $QUAY_IMAGE_NAME

#  hub_tag:
#    tag: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
#    owner: prometheus
#    commands:
#      - promu crossbuild tarballs
#      - promu checksum .tarballs
#      - promu release .tarballs
#      - mkdir $CIRCLE_ARTIFACTS/releases/ && cp -a .tarballs/* $CIRCLE_ARTIFACTS/releases/
#      - docker login -e $DOCKER_EMAIL -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
#      - docker login -e $QUAY_EMAIL -u $QUAY_LOGIN -p $QUAY_PASSWORD quay.io
#      - |
#        if [[ "$CIRCLE_TAG" =~ ^v[0-9]+(\.[0-9]+){2}$ ]]; then
#          docker tag "$DOCKER_IMAGE_NAME:$CIRCLE_TAG" "$DOCKER_IMAGE_NAME:latest"
#          docker tag "$QUAY_IMAGE_NAME:$CIRCLE_TAG" "$QUAY_IMAGE_NAME:latest"
#        fi
#      - docker push $DOCKER_IMAGE_NAME
#      - docker push $QUAY_IMAGE_NAME

workflows:
  version: 2
  node_exporter:
    jobs:
    - test
    - build
    - docker_hub_master:
        requires:
        - test
        - build
        filters:
          branches:
            only: master
